Restaurant_kitchen_services/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from kitchen.views import HomeView

urlpatterns = [
    path("", HomeView.as_view(), name="home"),  # головна сторінка
    path("admin/", admin.site.urls),
    path("kitchen/", include("kitchen.urls")),
    path("accounts/login/", auth_views.LoginView.as_view(template_name="registration/login.html"), name="login"),
    path("accounts/", include("django.contrib.auth.urls")),
]

kitchen/urls.py
from django.urls import path
from . import views

app_name = "kitchen"

urlpatterns = [
    path("", views.HomeRedirectView.as_view(), name="home"),
    # Dish
    path("dishes/", views.DishListView.as_view(), name="dish-list"),
    path("dishes/create/", views.DishCreateView.as_view(), name="dish-create"),
    path("dishes/<int:pk>/update/", views.DishUpdateView.as_view(), name="dish-update"),
    path("dishes/<int:pk>/delete/", views.DishDeleteView.as_view(), name="dish-delete"),

    # Chef
    path("chefs/", views.ChefListView.as_view(), name="chef-list"),
    path("chefs/create/", views.ChefCreateView.as_view(), name="chef-create"),
    path("chefs/<int:pk>/update/", views.ChefUpdateView.as_view(), name="chef-update"),
    path("chefs/<int:pk>/delete/", views.ChefDeleteView.as_view(), name="chef-delete"),

    # DishType
    path("dishtypes/", views.DishTypeListView.as_view(), name="dishtype-list"),
    path("dishtypes/create/", views.DishTypeCreateView.as_view(), name="dishtype-create"),
    path("dishtypes/<int:pk>/update/", views.DishTypeUpdateView.as_view(), name="dishtype-update"),
    path("dishtypes/<int:pk>/delete/", views.DishTypeDeleteView.as_view(), name="dishtype-delete"),

    # Ingredient
    path("ingredients/", views.IngredientListView.as_view(), name="ingredient-list"),
    path("ingredients/create/", views.IngredientCreateView.as_view(), name="ingredient-create"),
    path("ingredients/<int:pk>/update/", views.IngredientUpdateView.as_view(), name="ingredient-update"),
    path("ingredients/<int:pk>/delete/", views.IngredientDeleteView.as_view(), name="ingredient-delete"),
]

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}
sidebar.html

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <li class="list-group-item">
      User: <a href="#">{{ user.get_username }}</a>
    </li>
    <li class="list-group-item">
      <a href="{% url 'logout' %}?next={{ request.path }}">Logout</a>
    </li>
  {% else %}
    <li class="list-group-item">
      <a href="{% url 'login' %}?next={{ request.path }}">Login</a>
    </li>
  {% endif %}

  <br>

  <li class="list-group-item">
    <a href="{% url 'kitchen:dish-list' %}">All Dishes</a>
  </li>
  <li class="list-group-item">
    <a href="{% url 'kitchen:dishtype-list' %}">All Dish Types</a>
  </li>
  <li class="list-group-item">
    <a href="{% url 'kitchen:ingredient-list' %}">All Ingredients</a>
  </li>
  <li class="list-group-item">
    <a href="{% url 'kitchen:chef-list' %}">All Chefs</a>
  </li>
</ul>